import { ChangeEvent, useState } from "react";
import { Camera, Leaf, ShieldCheck, Upload } from "lucide-react";
import { Card, SectionEyebrow, Badge } from "../components/ui/primitives";
import { analyzeCropHealth, fileToBase64, CropHealthResult } from "../lib/api";
import { useI18n } from "../lib/i18n";

export default function CropHealth() {
  const { t } = useI18n();
  const [preview, setPreview] = useState<string | null>(null);
  const [loading, setLoading] = useState(false);
  const [result, setResult] = useState<CropHealthResult | null>(null);

  async function onFile(e: ChangeEvent<HTMLInputElement>) {
    const file = e.target.files?.[0];
    if (!file) return;
    setPreview(URL.createObjectURL(file));
    setResult(null);
    setLoading(true);

    try {
      const { base64, mimeType } = await fileToBase64(file);
      const res = await analyzeCropHealth(base64, mimeType);
      setResult(res);
    } catch (err) {
      console.error("Diagnosis failed", err);
      alert("Failed to analyze crop health image.");
    } finally {
      setLoading(false);
    }
  }

  return (
    <div className="max-w-5xl mx-auto px-4 sm:px-6 py-10">
      <SectionEyebrow>{t("cropHealth")}</SectionEyebrow>
      <h1 className="font-display text-3xl font-semibold text-forest-dark mb-1">{t("diagnoseLeaf")}</h1>
      <p className="text-ink-soft text-sm mb-8 max-w-2xl">
        Upload a photo of a leaf, fruit, stem or root. AGRINOVA checks for disease, pest damage, nutrient
        deficiency and water stress, and explains what to do next.
      </p>

      <div className="grid lg:grid-cols-2 gap-6">
        <Card className="flex flex-col items-center justify-center text-center min-h-[340px] border-2 border-dashed border-forest/20 bg-husk-dim/50">
          {preview ? (
            <img src={preview} alt="Uploaded crop" className="max-h-72 rounded-xl object-cover mb-4" />
          ) : (
            <span className="w-16 h-16 rounded-full bg-sprout-light text-forest flex items-center justify-center mb-4">
              <Camera size={26} />
            </span>
          )}
          <label className="cursor-pointer inline-flex items-center justify-center gap-2 rounded-full font-semibold bg-canopy text-husk hover:bg-forest transition-colors px-5 py-2.5 text-[15px]">
            <Upload size={16} /> {preview ? "Upload another photo" : t("uploadPhoto")}
            <input type="file" accept="image/*" className="hidden" onChange={onFile} />
          </label>
          <p className="text-xs text-ink-soft mt-3">JPG or PNG · leaves, fruit, stems or roots</p>
        </Card>

        <div>
          {!preview && (
            <Card className="h-full flex items-center justify-center text-center text-ink-soft text-sm p-10">
              Your diagnosis will appear here once you upload a photo.
            </Card>
          )}
          {loading && (
            <Card className="h-full flex flex-col items-center justify-center text-center p-10 gap-3">
              <div className="flex gap-1.5">
                {[0, 1, 2].map((i) => (
                  <span key={i} className="w-2 h-2 rounded-full bg-canopy animate-bounce" style={{ animationDelay: `${i * 0.12}s` }} />
                ))}
              </div>
              <p className="text-sm text-ink-soft">Analyzing image for disease, pests and stress signs...</p>
            </Card>
          )}
          {result && !loading && (
            <Card>
              <div className="flex items-start justify-between gap-3 mb-4">
                <div>
                  <p className="text-xs text-ink-soft mb-1">Severity: {result.severity}</p>
                  <h2 className="font-display text-xl font-semibold text-forest-dark">{result.disease}</h2>
                </div>
                <Badge tone={result.severity === 'None' ? 'canopy' : result.severity === 'Mild' ? 'amber' : 'alert'}>
                  {Math.round(result.confidence * 100)}% confidence
                </Badge>
              </div>

              <div className="space-y-4 text-sm">
                <div>
                  <p className="font-semibold text-forest-dark flex items-center gap-1.5 mb-1.5">
                    <ShieldCheck size={14} className="text-canopy" /> Recommended Treatment
                  </p>
                  <p className="text-ink-soft leading-relaxed">{result.treatment}</p>
                </div>
                {result.mode === 'gemini' && (
                  <p className="text-[11px] text-canopy font-medium mt-4 flex items-center gap-1">
                    <Leaf size={11} /> Analysis generated by live Gemini AI
                  </p>
                )}
              </div>
            </Card>
          )}
        </div>
      </div>
    </div>
  );
}
